# TODO: Adjust values to the correct ones for the rule
uppgift:
  id: 7028893f-c625-42e1-ab58-5891c0d6834e
  version: 1
  path: /regel/maskinell
  aktivitet: "Bedöma rätten till"

specifikation:
  id: a42ffaed-2f20-47e8-8499-f2f79ae2f45f
  version: 1
  namn: "Har kunden rätt till ... ?"
  uppgiftbeskrivning: "Kontrollerar om ..."
  verksamhetslogik: C
  roll: ANSVARIG_HANDLAGGARE
  applikationsId: 3.5.2
  applikationsversion: kontroll_folkbokford_arbetsgivare_1.0

regel:
  id: caf86a5f-9776-4fce-a854-8d365fa75067
  version: 1
  namn: "Har kunden ... "
  beskrivning: "Maskinell kontroll som ... "

lagrum:
  id: 6955bd9b-2019-4589-a460-7bcfd8a43eb5
  version: 1
  giltigFom: 2010-02-11
  forfattning: Husdjursbalken
  kapitel: 4
  paragraf: 7
  stycke: 2
  punkt: 3

utokadUppgiftsbeskrivning:
  beskrivning: "Maskinell kontroll som ..."
