name: Bundle Maven CI

on: [workflow_dispatch, workflow_call, push, pull_request]

jobs:
  call-workflow:
    uses: Forsakringskassan/.github/.github/workflows/bundle-maven-ci.yaml@bfb01f7611f5637d0464bbb5cdc02f2651119030 # main
    secrets:
      PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
      PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}

  validate-config:
    uses: Forsakringskassan/rimfrost-framework-regel/.github/workflows/validate-config.yaml@2e485e6f46b33020fcef46874dab2660344feb7b # 1.4.3
    with:
      framework-ref: '1.2.3'